function [features, featureNames] = buildKMeansPixelFeatures(rgb, config)
%BUILDKMEANSPIXELFEATURES Build pixel feature matrix used by RBC K-means.

rgb = im2double(rgb);
[imgHeight, imgWidth, channels] = size(rgb);
if channels ~= 3
    error("Input must be an RGB image.");
end

hsvImg = rgb2hsv(rgb);
labImg = rgb2lab(rgb);

R = rgb(:, :, 1);
G = rgb(:, :, 2);
B = rgb(:, :, 3);
S = hsvImg(:, :, 2);
V = hsvImg(:, :, 3);
L = labImg(:, :, 1);
A = labImg(:, :, 2);
BLab = labImg(:, :, 3);

sumRGB = R + G + B + eps;
rNorm = R ./ sumRGB;
gNorm = G ./ sumRGB;
bNorm = B ./ sumRGB;
BminusR = B - R;
RminusG = R - G;

[xGrid, yGrid] = meshgrid(0:max(imgWidth - 1, 0), 0:max(imgHeight - 1, 0));
xNorm = xGrid ./ max(imgWidth - 1, 1);
yNorm = yGrid ./ max(imgHeight - 1, 1);
spatialWeight = config.ml.kmeans.spatialWeight;

features = [
    L(:), ...
    A(:), ...
    BLab(:), ...
    S(:), ...
    V(:), ...
    rNorm(:), ...
    gNorm(:), ...
    bNorm(:), ...
    BminusR(:), ...
    RminusG(:), ...
    spatialWeight * xNorm(:), ...
    spatialWeight * yNorm(:)
];

features(~isfinite(features)) = 0;

featureNames = [
    "L", ...
    "A", ...
    "BLab", ...
    "S", ...
    "V", ...
    "rNorm", ...
    "gNorm", ...
    "bNorm", ...
    "BminusR", ...
    "RminusG", ...
    "X", ...
    "Y"
];

end
